FROM ubuntu
MAINTAINER Frank Behrens, fbehrens@gmail.com

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y wget

RUN wget -qO- https://raw.github.com/progrium/dokku/master/bootstrap.sh | bash
