# This is wc
#
# VERSION       0.42

# use the base image provided by dotCloud
FROM ubuntu

MAINTAINER Victor Coisne victor.coisne@dotcloud.com

# count lines with wc
ENTRYPOINT ["wc", "-l"]

# run with
